language: go

notifications:
  email: false

env:
  global:
    - secure: "GlPLJfSq5DsDp2zFTxi3151bF5wJbLWkSIAYsel9DwL9O5YRCASsV4XgRN9/DBC3hS/rbiB6tCCIZXuumufMg96YDboxINSBX8qlH6bqu20ybUXe9tg1BjazHgo7Lp/KOCKYt4VU1/qrMGQKOcxyl6moBmUp+GCHoYe86XVoi5A="
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
